### ISSUE TITLE
still missing wireless interface wlan0

### ISSUE THREAD

**Issue by Sheng2216** [sartura/replica#19]
Hi, 
We built a new image based on the updated master branch, however, during the tests, we found that **wlan0** interface is missing, and here is the error message that might be useful:

1. the result of `ip -a`

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether e4:5f:01:3b:56:25 brd ff:ff:ff:ff:ff:ff
>     inet 10.2.13.200/24 brd 10.2.13.255 scope global dynamic eth0
>        valid_lft 502sec preferred_lft 502sec
>     inet6 fe80::e65f:1ff:fe3b:5625/64 scope link 
>        valid_lft forever preferred_lft forever
> 3: enx000ec674b689: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
>     link/ether 00:0e:c6:74:b6:89 brd ff:ff:ff:ff:ff:ff

2. the result of `dmesg | grep cfg80211`

> [    2.792053] cfg80211: Loading compiled-in X.509 certificates for regulatory database
> [    2.810429] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
> [    2.815241] cfg80211: failed to load regulatory.db

3. the result of `dmesg | grep brcmfmac*`

> [    2.833267] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
> [    2.843291] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.txt failed with error -2
> [    2.843349] brcmfmac mmc1:0001:1: Falling back to sysfs fallback for: brcm/brcmfmac43455-sdio.txt
> [    3.847933] brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50

We tried to install tools like **network-manager** and **net-tools** as you suggested, but still cannot use these tools to manage wlan0 as it's missing. Could you provide some suggestions so we can bring back the wireless interface?

**Comment by Sheng-IoT** [comment]
@jela1337 Hi, sorry about the confusion caused by interface **enx000ec674b689** , I just want to clarify that it showed up there only because I was testing a USB hub with an ethernet port, once I unplug the USB hub, it will disappear.  By the way, we are testing the image on a CM4 with a carrier board and a network cards. The interface's name of that network card is enp1s0 in our case. 
here are the outputs:
1.  the output of **lshw**
[lshw.txt](https://github.com/sartura/replica/files/7386570/lshw.txt)
2. the full output of **dmesg**
[dmesg.txt](https://github.com/sartura/replica/files/7386665/dmesg.txt)
3. **udevadm info /sys/class/net/enx000ec674b689** （I don't think you will need it, but just in case）
[udevadm_enx000ec674b689.txt](https://github.com/sartura/replica/files/7386676/udevadm_enx000ec674b689.txt)
4. **udevadm_enp1s0** （again, just in case you might need it)
[udevadm_enp1s0.txt](https://github.com/sartura/replica/files/7386684/udevadm_enp1s0.txt)
