### ISSUE TITLE
Potential automatization of the Gentoo stage3 and repositories

### ISSUE THREAD

**Issue by lperkov** [sartura/replica#27]
Would it be possible to automate updating Gentoo stage3 and repositories by a cron job or something similar?

These are the commits:

https://github.com/sartura/replica/commit/e8c62fbc54f8bdafdf03859306ef1094f654e702
https://github.com/sartura/replica/commit/7e59648c67290b2d338fecbf9e903a731a6ddbae

**Comment by jsmolic** [comment]
Yes, we just have to keep in mind there is always a possibility of a breakage happening due to changes in upstream packages or new versions being added (this can especially happen if we restrict package versions, which we do now for some packages).\
Right now I update repositories manually since I like to verify all builds are succeeding before pushing to the `main` branch. On the other hand, problems due to upstream changes don't happen that often so we could certainly automate this process.

**Comment by robimarko** [comment]
I agree with @jsmolic, the reason why it's not done is to make sure it doesn't break stuff.
As we had bad experiences with new stuff being unmasked or stage not being synced with the main repo etc.

I am not really keen on making it automatic

**Comment by jpetrina** [comment]
I suggest we introduce weekly automated updates which are pushed as changes into a separate branch (e.g. `weekly`) where both Gentoo image and the repositories are updated. Although these builds may be successful, they would still be merged manually.

@robimarko @jsmolic do you think this could work?

**Comment by robimarko** [comment]
Yeah, as they could even suceed building but then break something.
So it still needs to be manually tested but at least saves the need to manually prepare stuff
