### ISSUE TITLE
how to add python 3 before the "make" process?

### ISSUE THREAD

**Issue by Sheng-IoT** [sartura/replica#8]
Distribution: Ubuntu 20.04
RAM: 8G
Issue description: Hi, I followed the instruction on how to generate an image for raspberry 4, but I found the the default image doesn't come with package manager Portage. I tried to add "*dev-lang/python:3.8" to the "package.mask" file as Python 3 is required before installing Portage according to [Portage's documentation](https://wiki.gentoo.org/wiki/Portage), but I got this error
![image](https://user-images.githubusercontent.com/87348555/132159433-b7a15374-6be9-4722-8b8e-1bb6cec54ea9.png)
and also my "package.mask" file looks like this 
![image](https://user-images.githubusercontent.com/87348555/132159481-1cb41e6a-e2bd-4e6a-a8e0-0f644817a49d.png)
Could you please let me know how to add Portage and Python 3 before the "make" process? Appreciate it!

**Comment by robimarko** [comment]
Hm, CTARGET is incorrect in your case that is why it's failing.
Can you share the full make command?

Portage is deliberately left out by default as it requires the whole toolchain on the device.
Why are you adding stuff to package.mask, that will disable it instead of enabling it?

**Comment by Sheng-IoT** [comment]
thank you so much for your reply, I changed the CTARGET to the correct one, and now I am waiting for the make command to finish. it seems everything works just fine for now...
But I still have one question, how can I add a package manager tool, something like apt? I know by default Gentoo uses Protege, but since you said portage is deliberately left out by default, how am I supposed to manage packages?
Thank you so much for your time!

**Comment by robimarko** [comment]
Gentoo is a source-based distribution, meaning it's designed to build everything from the source, including packages.
Portage was left intentionally, as usually there is no need for the Replica use case and it has a lot of dependencies that don't fit all of the targeted devices due to RAM and storage constraints.
But, nothing prevents you from including Portage as a package along with the toolchain as APT is not supported in Gentoo.
There is dpkg package but on its own, it doesn't really do much.
